stages:
  - build
  - test
  - deploy

# Job para compilar el c贸digo
build:
  stage: build
  script:
    - echo "Compilando el c贸digo..."
    # Reemplaza el siguiente comando con el script real para compilar tu proyecto
    - echo "Compilaci贸n completa."

# Job para pruebas unitarias
test:
  stage: test
  script:
    - echo "Ejecutando pruebas unitarias..."
    # Reemplaza el siguiente comando con el script real para ejecutar pruebas unitarias
    - sleep 30  # Simula un tiempo de espera para la ejecuci贸n de pruebas
    - echo "Pruebas unitarias completadas."

# Job para desplegar en Vercel
deploy:
  stage: deploy
  script:
    - echo "Desplegando en Vercel..."
    - npm i -g vercel  # Instalar Vercel CLI
    - vercel --prod --token $VERCEL_TOKEN  # Despliegue usando Vercel CLI
  only:
    - main  # Desplegar solo cuando se haga push a la rama main

