stages:
  - build
  - test

# Job para compilar el c贸digo
build:
  stage: build
  script:
    - echo "Compilando el c贸digo..."
    # Reemplaza el siguiente comando con el script real para compilar tu proyecto
    - echo "Compilaci贸n completa."

# Job para pruebas unitarias
test:
  stage: test
  script:
    - echo "Ejecutando pruebas unitarias..."
    # Reemplaza el siguiente comando con el script real para ejecutar pruebas unitarias
    - sleep 30  # Simula un tiempo de espera para la ejecuci贸n de pruebas

